version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16-stretch
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0c:29:10:f0:0e:fd:f8:a7:88:c1:0e:a3:1a:23:71:76"
      - checkout
      - run: echo "Building..."
      - run: npm install
      - run: npm run build
      - run:
          name: Test the build
          command: |
            if [ -f themes/wacoal/dist/assets.json ]; then
              echo "Build succeeded";
            else
              echo "Build failed, assets.json file missing"; exit 1
            fi
      - run:
          name: Remove local dev only code
          command: sed --in-place '/LOCALDEV START/,/LOCALDEV END/{//p;d;}' themes/wacoal/functions.php
      - deploy:
          name: Deploy -built branch to github
          command: bash <(curl -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy.sh")
